version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    steps:
      - checkout
      - run:
          name: "Install prerequisites"
          command: sudo apt-get update -y
      - run:
          name: "Build JDeskew"
          command: pip install -e .[dev]
      - run:
          name: "Run test"
          command: |
            coverage run -m pytest tests/test.py
            coverage report -i
            coverage xml -i
      - run:
          name: "Upload coverage"
          when:
            not:
              equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml

workflows:
  main-flow:
    jobs:
      - build-and-test
  code-rot-check-daily:
    triggers:
      - schedule:
          cron: "1 18 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-and-test
